name: PHPCS checks
on:
  push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - uses: "ramsey/composer-install@v2"
      - name: Run PHPCS checks
        run: php -d memory_limit=1G ${GITHUB_WORKSPACE}/vendor/bin/phpcs -s --standard=${GITHUB_WORKSPACE}/.phpcs.xml.dist